# Generated by Django 5.1.7 on 2025-03-30 15:54

import tests_example.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, help_text='type description or leave empty', null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=tests_example.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(help_text='type title', max_length=75, unique=True),
        ),
    ]
