name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: my_site.settings
      PYTHONUNBUFFERED: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pylint-django

    - name: Run pylint
      run: |
        pylint --load-plugins=pylint_django my_site

    - name: Run Django tests
      run: |
        python manage.py migrate --noinput
        python manage.py test
